site_name: TeoLang
site_description: 'A programming language for kids to get started.'
site_author: 'Teo team'
docs_dir: docs/
repo_name: 'teolang/teo'
repo_url: 'https://github.com/teolang/teo'
plugins:
  - social
theme:
  name: 'material'
  features:
    - content.code.annotate
