site_name: TeoLang
site_description: 'A programming language for kids to get started.'
site_author: 'Teo team'
docs_dir: docs/
repo_name: 'teolang/teo'
repo_url: 'https://github.com/teolang/teo'
nav:
    - Home: index.md
    - Documentation:
      - Let: commands/let.md
      - Print: commands/print.md
theme:
  name: 'material'
