name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up GCC
      uses: msys2/setup-msys2@v2
      if: runner.os == 'Windows'
    - name: Making CParse
      shell: bash
      run: make release -C cparse
    - name: Building (Windows)
      if: runner.os == 'Windows'
      shell: bash
      run: |
        cmake -G "MinGW Makefiles" .
        make
    - name: Building (Linux)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        cmake .
        make

