name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Caching CParse
      uses: actions/cache@v3
      id: cparse-cache
      with:
        path: |
          cparse/core-shunting-yard.o
          cparse/builtin-features.o
        key: cparse-${{ runner.os }}-${{ hashFiles('cparse/') }}
    - name: Caching Build (Windows)
      uses: actions/cache@v3
      if: steps.cparse-cache.outputs.cache-hit == 'true' && runner.os == 'Windows'
      id: win-build-cache
      with:
        path: ./build/main.exe

        key: cparse-${{ runner.os }}-${{ hashFiles('./*.cpp', './*.h', 'CMakeLists.txt') }}
    - name: Caching Build (Linux)
      uses: actions/cache@v3
      if: steps.cparse-cache.outputs.cache-hit == 'true' && runner.os != 'Windows'
      id: linux-build-cache
      with:
        path: ./build/main.exe

        key: cparse-${{ runner.os }}-${{ hashFiles('./*.cpp', './*.h', 'CMakeLists.txt') }}
    - name: Set up GCC
      uses: msys2/setup-msys2@v2
      if: runner.os == 'Windows' && ${{ steps.cparse-cache.outputs.cache-hit != 'true' || steps.win-build-cache.outputs.cache-hit != 'true'}}
    - name: Get number of CPU cores
      if: ${{ steps.cparse-cache.outputs.cache-hit != 'true' || steps.win-build-cache.outputs.cache-hit != 'true'}}
      uses: SimenB/github-actions-cpu-cores@v1
      id: cpu-cores
    - name: Making CParse
      shell: bash
      if: steps.cparse-cache.outputs.cache-hit != 'true'
      run: make release -C cparse -j${{ steps.cpu-cores.outputs.count }}
    - name: Building (Windows)
      if: runner.os == 'Windows' && steps.win-build-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cmake -G "MinGW Makefiles" . -B build
        cd build && make -j${{ steps.cpu-cores.outputs.count }}
    - name: Building (Linux)
      if: runner.os != 'Windows' && steps.linux-build-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cmake . -B build
        cd build && make -j${{ steps.cpu-cores.outputs.count }}
    - name: Archive Windows build
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v3
      with:
        name: Windows build
        path: build/main.exe
    - name: Archive Linux build
      if: runner.os != 'Windows'
      uses: actions/upload-artifact@v3
      with:
        name: Linux build
        path: build/main
        

