name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: echo "Nothing to do"
    - name: Setup (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        echo "PATH=$PATH:C:\msys64\mingw64\bin" >> $GITHUB_ENV
    - name: Build for ${{matrix.os}}
      run: make
